---
title: "Accessing the course through Github"
author: "Patrick Mathias"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## What is version control?

Version control is a "system that records changes to a file or set of files over time so that you can recall specific versions later" [(Git Documentation)](https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control). 

Why is this helpful?
- When collaborating on code, the versions of the code that two or more collaborators are using can quickly get out of sync.
- Even if you are not collaborating you probably want to track changes to your code and have the ability to revert to a previous version of your code

Git is a common version control system for which RStudio offers integration. Git is a useful tool but it does take some time to get the hang of using it efficiently. In this course we will introduce some functionality but will focus on accessing a Github repository. There are some good resources to learn more [here](https://swcarpentry.github.io/git-novice/01-basics/) and [here](https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control).

We created a Github repository for this course to help us collaborate but it also allows us to make the content widely available and provide a convenient way for you to access the materials.

## Accessing the course repository via RStudio

RStudio provides built-in functionality within the creation of a new project to obtain the contents of a Github repository. Let's pull the project into RStudio:

1. Navigate to the File menu and select New Project
2. Select Version Control in the Create Project prompt
3. Select Git
4. Paste the following URL in the Repository URL prompt: https://github.com/pcmathias/MSACL-intermediate-R-course
5. Give the project directory a name, eg. intermediate-R-course
6. Find a location where you want your course contents to live and select the directory with the Browse button
7. Create Project

Now you can see the directory contents for the project in your Files window and can select specific files to work with for individual lessons.