---
title: 'Lesson 8: Beyond the csv -- parsing xml and json files'
author: "Adam Zabell"
date: "12/28/2017"
output: html_document
---

```{r setup, include=FALSE}
rootDir <- "/Users/azabell/Dropbox/R/"
knitr::opts_chunk$set(echo = TRUE)
library(xml2)
library(jsonlite)
```

# Flat and Structured Files
read_csv read_tsv and read.xlsx are flat, but not really since we regularly use the first row as a column header, giving structure to the data

for the most part, databases are far more structured than that, where each element in the datbase must contain a value.

the details of database construction are well beyond the scope of this class. But the resulting file from a database query is typically in XML or JSON format. Parsing from that format into a data.frame

## The extensible markup language (xml)
Looks a lot like html, because html is (by and large) a subset of xml. But html permits some shortcuts which xml does not, and xml doesn't have a restricted set of tags. 

cd <- read_xml("https://www.w3schools.com/xml/cd_catalog.xml")
cd.list <- as_list(cd)
cd.rows <- length(cd.list)
cd.names <- list(names(cd.list[[1]]))
cd.df <- data.frame(matrix(unlist(cd.list), nrow=cd.rows, byrow=TRUE, dimnames=list(NULL,cd.names)),stringsAsFactors=FALSE)

## The javascript object notation (json)
A web browser can only send one thing, or retrieve one thing, at a time. The most complex online form has to be reduced to a single string, and then unpacked on the other side. It tends to be more lightweight than xml, and looks very different, but operates on the same principle of first naming a thing, and then giving it a value.

colr <- fromJSON("https://raw.githubusercontent.com/corysimmons/colors.json/master/colors.json")
colr.rows <- length(colr)
colr.df <- data.frame(matrix(unlist(colr), nrow=colr.rows, byrow=TRUE),stringsAsFactors=FALSE)
names(colr.df) <- c("R","G","B","T","name")
colr.df$name <- names(colr.rows)

## Solving problems
The most common problem is that numbers are now text strings. Jumping ahead to the next lesson, the fix is
cd.df$PRICE %<>% map_dbl(as.numeric)

There are a lot of other problems that could happen, because each entry in the xml or json file is an independent description. There may be an element not present in every entry (not including a price for a CD), or multiple elements within an element (two artists for a CD). Either is disasterous; conversion will now be wildly offset.

Most problems should be solved on the query-side of the equation, to confirm the query was built correctly and that the database is populated as expected. But, as with the above "two artists for one CD" it is possible that your data isn't as data.frame friendly as you would like. It might be helpful to troubleshoot the retrieved query with some basic checks on the data that you do have.

every entry (which becomes a 'row' in the data.frame) has the same number of elements (which becomes a 'column').
every entry has the same names for their elements
every element has only one value



# Summary